const gravity = new BABYLON.Vector2(0, -9.8);
const flightForce = 5; // The amount of force applied when the "fly" button is pressed

const greetings = [
    "It's a Foobar!",
    'It\'s a bird!',
    'It\'s a plane!',
    '1000% more Cube!',
    'A Whole New Dimension!',
    'What? You never saw a cube fly before?',
    'Gravity is just a suggestion.',
    'You can now see the gravity of the situation.',
    'Single key ought to be enough for anybody.',
    'Who gives the floppying bird?',
    'I believe I can fly!',
    'Lift off!',
    'What the fork?',
    'Killing me softly with this wall...',
    'I\'m a barbie cube in a barbie world...',
    'Not an usual bird.',
    'Cube is a new circle',
    'My favorite art movement is cubism.',
    'Spacing out...',
    'Return of the space',
    'This is a touchy subject.',
    'I like to wall it, wall it.',
    'Have I got the news for you!',
    'I for one would like to welcome our British overlords.',
    'Don\' fly to high.',
    'Don\'t panic!',
    'Just miss the ground.',
    'I\' not a Hemingway, but I can fly.',
    'Into the crack!',
    'I never read README.',
    'Am I the cube or it\'s this just a dream?',
    'Is this just a cube or is this fantacy?',
    'Cube is just an overachieving square.',
    'If my edges are rounded, am I still a cube?',
    'Nobody ever wants to see a floppy cube',
    'Flapping of flopping?',
    'It\'s Cube Tastic',
    'A Whole New World',
    'Cubing is my passion!',
    'Never saw a number I couldn\'t cube',
    'Would a cube smell as sweet under any other name?',
];
